### ISSUE TITLE
Doen't work on latest insider preview

### ISSUE THREAD

**Issue by Mahdi-Noor-Hasan** [krlvm/BeautySearch#11] opened 2021-03-30 08:45 UTC
[winver](https://i.imgur.com/WuISyx1.png)

**Comment by krlvm** [comment] 2021-03-30 11:58
:(
I will check it once 20H1 hits Stable channel

**Comment by krlvm** [comment] 2021-03-30 11:59
:(
I will check it once 20H1 hits Stable channel.
Which error are you getting?

**Comment by bluelhf** [comment] 2021-05-12 12:32
Can confirm on Version Dev 21376.1  
No error, but none of the options selected with the installer are applied, even after killing the SearchApp process

Steps to reproduce:

1. Install the latest insider preview build
2. Start BeautySearch.exe as Administrator
3. Select the following settings:
![image](https://user-images.githubusercontent.com/52505120/117974700-8d96ac80-b336-11eb-8a3f-0cd88c7a4647.png)  
4. Click (Re)install, and see that the success message box appears:
![image](https://user-images.githubusercontent.com/52505120/117974785-a3a46d00-b336-11eb-8f7b-42905d472b5e.png)  
5. Search something in Windows Search, and see that the dark theme was not applied:
![image](https://user-images.githubusercontent.com/52505120/117974867-bae35a80-b336-11eb-9464-b3cb05457d5a.png)

**Comment by julioHerrera515** [comment] 2021-06-10 14:18
Hi, my name is Julio, did you solve your problem?

**Comment by krlvm** [comment] 2021-06-12 21:29
**BeautySearch still works even on the latest Insider Preview (Build 21390).**

The problem is with accessing the system directory that contains Search UI files (`C:\Windows\SystemApps\Microsoft.Windows.Search_cw5n1h2txyewy\cache\Local\Desktop`, hereinafter - folder), you may need to take ownership of it manually:

1. Open folder properties, go to Security tab:
![image](https://user-images.githubusercontent.com/51774833/121789138-85a38400-cbe4-11eb-9993-618d6d133e2f.png)
2. Take complete ownership (check the checkbox before):
![image](https://user-images.githubusercontent.com/51774833/121789220-2abe5c80-cbe5-11eb-81d9-d3f08740e501.png)
3. After closing the dialog and opening it again, take full access:
![image](https://user-images.githubusercontent.com/51774833/121789246-69ecad80-cbe5-11eb-99dc-7f622acb1995.png)
![image](https://user-images.githubusercontent.com/51774833/121789314-0616b480-cbe6-11eb-8ab0-085e367df9c5.png)
4. Install BeautySearch using the Installer
5. Done
![image](https://user-images.githubusercontent.com/51774833/121789386-8b9a6480-cbe6-11eb-9657-b5b90fd6ff38.png)

Nevertheless, talking about post-20H1/20H2/21H1 builds, I've noticed strange looking - I will fix it when 21H2 will reach Stable channel if it won't be an update like 20H2 or 21H1.

**Closed by krlvm** 2021-06-12 21:29 UTC
Labels: bug, enhancement, help wanted, wontfix
