### ISSUE TITLE
UWP apps' icons become blurry when "Remove background from UWP application icons" feature is enabled

### ISSUE THREAD

**Issue by bywkgexmkiltxh** [krlvm/BeautySearch#45] opened 2023-05-19 18:10 UTC
![2](https://github.com/krlvm/BeautySearch/assets/127624994/02e8a70a-df63-472d-9495-91777ef1fb06)
_The left one is the default one, the right one is BeautySearch injected_

**Comment by krlvm** [comment] 2023-05-19 19:12
Duplicate of #5

Search App provides us a lower-resolution icons, we are upscaling them.

**Comment by bywkgexmkiltxh** [comment] 2023-05-20 13:55
> Duplicate of #5
> 
> Search App provides us a lower-resolution icons, we are upscaling them.

May I ask you to add an option to not change the size so it wouldn't get this blurry since it isn't upscaled. It doesn't have to get bigger than the original in my opinion
If you're not eager then don't do it, that was a **suggestion** anyway
![immersivecontrolpanel](https://github.com/krlvm/BeautySearch/assets/127624994/17130e60-979c-4022-aae3-37ab05226c20)
_I'm asking how it should look like is below_
![Search](https://github.com/krlvm/BeautySearch/assets/127624994/d69263aa-51f5-46f5-b647-cabf50100fba)
> If you're not eager then don't do it, that was a **suggestion** anyway

**Comment by krlvm** [comment] 2023-05-20 14:28
Seems worse TBH, but you can achieve this by editing out [this](https://github.com/krlvm/BeautySearch/blob/daf54d02e9a8d3216abbe0947303cb40f357ec5b/BeautySearch/Scripts/BeautySearch.js#L424) line from `%WinDir%\SystemApps\<...>Search<...>\cache\Local\Desktop\BeautySearch.js

**Closed** 2023-05-20 14:28 UTC
Labels: question
